### ISSUE TITLE
Need "created_at" variable in mapping

### ISSUE THREAD

**Issue by acircleda** [making-data-science-count/TidyTuesday-Analysis#3]
I am trying to analyze the change in code classifications by week (over time), but the file used to create the tidycode_output dataframe, "mapping.csv", is missing that variable. I cannot locate the .R file that actually create the mapping file. Can you either point me in the right direction or add that variable?

**Comment by jrosen48** [comment]
Will take a look.

**Comment by acircleda** [comment]
I did not find the mapping code, but I did get the created_at variable.
