### ISSUE TITLE
move to making-data-science-count?

### ISSUE THREAD

**Issue by jrosen48** [making-data-science-count/TidyTuesday-Analysis#4]
Thoughts on moving this repository over to the [making-data-science-count](https://github.com/making-data-science-count) organization?

Just did this for another repo (to another, project-specific organization); instructions here: https://help.github.com/en/github/administering-a-repository/transferring-a-repository

**Comment by acircleda** [comment]
I will work on this tomorrow.

**Comment by acircleda** [comment]
I got the message "You don’t have the permission to create public repositories on making-data-science-count"

**Comment by acircleda** [comment]
Done!
